### ISSUE TITLE
进了你的tg群看了下，延迟很严重，这个和你的vps有关吗？

### ISSUE THREAD

**Issue by dayunnas** [slippersheepig/hostloc2tg#1]
进了你的tg群看了下，延迟很严重，这个和你的vps有关吗？还有，能不能图文一起，这样就省的进论坛了

**Comment by slippersheepig** [comment]
> 进了你的tg群看了下，延迟很严重，这个和你的vps有关吗？还有，能不能图文一起，这样就省的进论坛了

1.可能是黑五太多新帖了，我的代码爬得太快，触发了hostloc的防御机制，导致1天多没有获取到新帖；正常情况是约3分钟获取一次
2.已尝试添加展示图文功能
